apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k2fvxd18s-nodejs 
  janus-idp.io/tekton: k2fvxd18s-nodejs
  backstage.io/kubernetes-id: k2fvxd18s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2fvxd18s-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml